### PR TITLE
implementing fixes

### PR DESCRIPTION
**Pull request by fbele**
Implementing pending fixes. Most of the changes are commented in the source code.

### CODE REVIEW

**Comment by Tommertom** [comment]
@fbele   Thanks for this - just a quick q- you are using mkcert, is this because of development purposes? This does not affect a production build? And `npm run preview` does not suffice to test (without this package)? Maybe add a comment in vite-config to explain why it is there?

I am not familiar with this package, that is why I ask?

**Comment by fbele** [comment]
> @fbele Thanks for this - just a quick q- you are using mkcert, is this because of development purposes? This does not affect a production build? And `npm run preview` does not suffice to test (without this package)? Maybe add a comment in vite-config to explain why it is there?
> 
> I am not familiar with this package, that is why I ask?

Hi @Tommertom, yes this package is solely for development purposes. In order for `beforeinstallprompt` event to work properly, the app needs to run on https protocol. If you configure Vite to use https protocol and then use `npm run preview`, the browser will deny access to the app because there is no certificate for localhost. The mkcert injects a provisional (unsigned) certificate so you can view the built app without browser rejecting access to it.
Of course as a developer you can use different methods to run and view app, but if you use `npm run preview` this package is needed in order for it to work.
I did a short comment on line 50 in `vite.config.js`. You're welcome to supplement it if you feel it's not explanatory enough.

**Comment by fbele** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> Name 	Status 	Preview 	Comments 	Updated (UTC)
> **ionic-sveltekit-ssr-demo** 	❌ Failed ([Inspect](https://vercel.com/tommertom/ionic-sveltekit-ssr-demo/DFjp17pq3ydRwuCJcMvkFzaFM77i)) 			Jul 21, 2023 1:12pm

I see that there are no conflicts, but I cannot investigate why it didn't get deployed as I don't have permissions for it.
I guess you can take a look and fix what needs fixing?

**Comment by Tommertom** [comment]
I will take a look

**Comment by Tommertom** [comment]
Error message:


<html>
<body>


error during build:
--
15:12:50.897 | Error: Could not load /vercel/path0/src/lib/components/LandingPage/Landing.svelte (imported by src/routes/+page.svelte): ENOENT: no such file or directory, open '/vercel/path0/src/lib/components/LandingPage/Landing.svelte'
15:12:50.943 | Error: Command "npm run build" exited with 1


</body>
</html>


By the way, I am a bit unfamiliar with this integration with Vercel. Did not expect it to fire on the PR. So please bear with me while I try to resolve it with you! :)

**Comment by fbele** [comment]
There is nothing much I can do here. In source of the repo the file is clearly there and referenced properly.
I think the issue is that we use `adapter-static` for building the app and not the `adapter-vercel` and for that afaik one needs to make few configurations in Vercel. Check out this video: https://www.youtube.com/watch?v=SUrFDhhsJNo
She explains it more towards the end of the video.

**Comment by Tommertom** [comment]
> There is nothing much I can do here. In source of the repo the file is clearly there and referenced properly. I think the issue is that we use `adapter-static` for building the app and not the `adapter-vercel` and for that afaik one needs to make few configurations in Vercel. Check out this video: https://www.youtube.com/watch?v=SUrFDhhsJNo She explains it more towards the end of the video.

Killed the Vercel project - seemed the easiest way

**Pull request merged**
